source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
target 'SMLElevationView', :exclusive => true do
  pod "SMLElevationView"
end

target 'Tests', :exclusive => true do
  pod "SMLElevationView"

  pod 'FBSnapshotTestCase'
end
